### calling root api end point
GET http://localhost:8000/


### calling get method on task api end point
GET http://localhost:8000/api/v1/task/
### calling post method on task api end point
POST http://localhost:8000/api/v1/task/
Content-Type: application/json

    {
      "task": "last check",
      "hr": "1"
    }


### calling put method on task api end point
PUT http://localhost:8000/api/v1/task
Content-Type: application/json

{
  "_id":"63e02ab109ffc8f43a399e9a",
  "type":"entry"
}
### calling patch method on task api end point
PATCH http://localhost:8000/api/v1/task
### calling Delete method on task api end point
DELETE http://localhost:8000/api/v1/task
Content-Type: application/json

  {
      "ids":["63e030ca110984d991bcca3e","63e04b652114e5a90136c3d7"]
    }